import { IconTypes } from "@/styles/theme/type";
import Head from "next/head";

import { Hero, FeatureBox } from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <div className="container mx-auto">
        <div className="flex flex-wrap gap-[30px]">
          <FeatureBox
            icon={IconTypes.QrCode}
            title="Kolay Kullanım"
            detail="Telefon kamerası ile QR kodu okutarak, kullanıcı dostu arayüzlü menüye hızlı ulaşabilirsiniz."
          />
          <FeatureBox
            icon={IconTypes.QrCode}
            title="Kolay Kullanım"
            detail="Telefon kamerası ile QR kodu okutarak, kullanıcı dostu arayüzlü menüye hızlı ulaşabilirsiniz."
          />
          <FeatureBox
            icon={IconTypes.QrCode}
            title="Kolay Kullanım"
            detail="Telefon kamerası ile QR kodu okutarak, kullanıcı dostu arayüzlü menüye hızlı ulaşabilirsiniz."
          />
          <FeatureBox
            icon={IconTypes.QrCode}
            title="Kolay Kullanım"
            detail="Telefon kamerası ile QR kodu okutarak, kullanıcı dostu arayüzlü menüye hızlı ulaşabilirsiniz."
          />
          <FeatureBox
            icon={IconTypes.QrCode}
            title="Kolay Kullanım"
            detail="Telefon kamerası ile QR kodu okutarak, kullanıcı dostu arayüzlü menüye hızlı ulaşabilirsiniz."
          />
          <FeatureBox
            icon={IconTypes.QrCode}
            title="Kolay Kullanım"
            detail="Telefon kamerası ile QR kodu okutarak, kullanıcı dostu arayüzlü menüye hızlı ulaşabilirsiniz."
          />
        </div>
      </div>
    </>
  );
}
